### List Events

GET https://eventmakers-api.vercel.app/api/events


### List Events by User

GET https://eventmakers-api.vercel.app/api/events?userid=83257de4-5397-4993-be7f-a194f2640d1d

### Single Event

GET https://eventmakers-api.vercel.app/api/events/6f0701e1-d61c-446c-ab04-9503a56ef46d

### Create Event

POST https://eventmakers-api.vercel.app/api/events

{
    "name": "Drone Photography 2023",
    "description": "Lezzgoo",
    "location": "Giri Hills",
    "date": "2023-11-23",
    "authorId": "83257de4-5397-4993-be7f-a194f2640d1d"
}

### Join Event
POST https://eventmakers-api.vercel.app/api/join-events

{
    "name": "Bintang di Langit",
    "email": "bintangjos@gmail.com",
    "phone": "-",
    "eventId": "f4563880-81de-457d-bf19-9ccaf181f1f8"
}